spring:
  application:
    name: event-recommender

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.eventrecommender: INFO
